version: '3.9'
services:
  postgres:
    container_name: postgres
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=cash_receipt
    networks:
      - backend
  app:
    container_name: cash-receipt
    image: cash-receipt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - backend
networks:
  backend:
    driver: bridge